### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by riprobins** [n8io/ultimate-media-server#2]
I've got up to the step 
sudo PIA_USER=user PIA_PASS=pass npm run docker

and get the following error

Starting ultimatemediaserver_shares_1
Starting ultimatemediaserver_plexpy_1
Starting ultimatemediaserver_plex_1
Creating ultimatemediaserver_sabnzbd_1
ERROR: invalid IP address in add-host: "localhost"

Not sure what to check next

**Comment by n8io** [comment]
My apologies @grobins, I have not maintained this package for a while. However there is still hope if you are up for an adventure.

http://blog.n8io.com/setting-up-a-plex-media-server-in-the-cloud/
