### ISSUE TITLE
Transmission URL 

### ISSUE THREAD

**Issue by fathermahoney** [n8io/ultimate-media-server#4]
Can't get the web UI for Transmission to come up. It's not showing up on port 8091 or 9091 (as other Transmission projects have it). Any ideas?

**Comment by n8io** [comment]
Are you running with the appropriate PIA credentials?

**Comment by fathermahoney** [comment]
I leave it blank "without authentication" when I run the startup script. Would that prevent it from spinning up?

**Comment by n8io** [comment]
Yes because the docker image used to run transmission is specifically for protecting your privacy behind a VPN.
